---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.0.150
    iqn: iqn.2000-01.com.synology:derpnas.mariadb-data.8bb55a3736
    lun: 1
    fsType: ext4
    chapAuthDiscovery: false
    chapAuthSession: true
    secretRef:
      name: chap-secret
