---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: radarr
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:3.0
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 6.0.2
  values:
    radarr:
      image:
        organization: linuxserver
        repository: radarr
        tag: 3.0.0.3966-ls26
        pullSecret: dockerhub-registrycreds
      env:
        TZ: America/Chicago
        UMASK_SET: "022"
        PUID: "1024"
        PGID: "100"
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: traefik-default-middlewares-chain@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls.options: traefik-secure-tlsoptions@kubernetescrd
        hosts:
        - host: radarr.nathanpawelek.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: nathanpawelek-com-tls
      service:
        type: ClusterIP
        port: 7878
      configPath: /config
      persistence:
        type: statefulset
        config:
          enabled: true
          existingClaim: radarr-config
        media:
          enabled: false
      additionalVolumes:
      - name: complete
        nfs:
          path: /volume1/Complete
          server: 192.168.0.150
      additionalVolumeMounts:
      - mountPath: /complete
        name: complete
      resources:
        requests:
          memory: 250Mi
        limits:
          memory: 500Mi
