---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: galera-helm-values
  namespace: galera
spec:
  encryptedData:
    values.yaml: AgANgTBFmjmxQ5TTFdm4GwzLVtLX1y2k4HgwjfX14MhfWexstDPaxxbxEAkBfFlfXBmzoyIsVOTy73/wj2gNvvuTsiLFpW6RM5KLqqnPM98nP9XOwA4K1eqI08NN0da88Ix/26vCqBxm6ePJatzTwV0GxMh9A70cPUZcyHfqAlm4OxHIB74W6HYVrPg3vghCb7jTrWN9SFhbqZSa8xo+Poome/FP2ABP80CqbhLqqJ48pgoXW25Fudmg/+NWvpdMOhiXlHaXWidFJdtMo7hhnS3UNQZ5B8pUAVq32lxY7c1mmqmfzEGo/oDPxv8kFgQkFQA/xb8jEKBB7pnkKgeSgfI8IG9h1dieLwi/onjUTf23mHYqVVLhl54G32ng5LVGgmsRGqRGqb+f1hbik99UZooNKnnfyUiRGTlc5CsKiPOPhSP9t3lSdMmEFNXkyHJHgLj4jnek+Lj+tcSNsZgXMEuJUQ7XwrlUtj4q2Q5u8nsWk7gXBkTla8TTHMOtRSnDIRHNo26NuWQk19AyxzEBwRd+BtVneu1NUCTqCAsQdEmzpcI1n0jf4cTjYR+6kJeKDzP8Br4mk4VpHPjT1062g3hf1lP9sZ6ZVwPYcp+orJWV2nhTm/ZB3VAzyI3qaThmjSir9wxddVrOr5UKmH1Pu1RQMCPq0+WFbrxh+PcWp3hjFZMfSfiVQjU3ADDTMCHHRHSgvewayZbx9u1TXJc5NsZc5LWYZ8IoxF6tyqPmqloKsNdKgMN5apkE4ggf78ih5aZ+P5ydJx+52CT2t71lXYrbuRG3nfrL0B+IqeUHoOxrpa7sTQHDJOjc1hHf3NvX2WZsTq3mjStS4VgNkCbSbsRssCZwQ0V+RNM0n+kNGx9034SvkVGYXYTOlWbsYcnfZd7uArJ/jxWEgbg9ej3acZFDQoESJVGFIp33ASw4RqGNjSUChHJ/0QJfoltQ31qyb5S7roHFvMCqenyx1V+OfOVSFI5t9GiA2RSYclMPADWMfdjrXroLJIpzg1hixtDebXbG4OPjzNf05NljJKZwhR2F44taP/834x5aKUuP2Tl2mC23OgsU9OMc+yXAQ/8NHDhri6IkjX4w6H3tu6oWzgjVgMUXr7r9aqerrV3ptEXyPn5Pqy3WwyKNUYOjrjbh0mYJ7EB7NEaF6bqM5ORfPqLK/QgccGdktpnEh+bF8y9GZjGkt7SCSWN95aXgRmO+H7mgDQMvXl5ssb8a6MPP9Q==
  template:
    metadata:
      creationTimestamp: null
      name: galera-helm-values
      namespace: galera
    type: Opaque
