---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resilio-config
  namespace: resilio
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
