---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  maxHistory: 3
  interval: 10m0s
  suspend: false
  chart:
    spec:
      chart: node-feature-discovery
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: 2.0.0
  values:
    image:
      repository: raspbernetes/node-feature-discovery
      tag: v0.7.0
      pullPolicy: IfNotPresent
    sources:
    # - cpu
    - custom
    # - iommu
    # - kernel
    # - local
    # - memory
    # - network
    # - pci
    # - storage
    # - system
    # - usb
    config: |
      sources:
        custom:
        - name: "intel-gpu"
          matchOn:
          - pciId:
              class: ["0300"]
              vendor: ["8086"]
        - name: "amd-gpu"
          matchOn:
          - pciId:
              class: ["0300"]
              vendor: ["1002"]
    master:
      replicaCount: 1
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: ""
        effect: NoSchedule
    worker:
      tolerations:
      - key: kubernetes.io/arch
        operator: Equal
        value: amd64
