---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra-config
  namespace: hydra
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
