---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chap-secret
  namespace: lazylibrarian
spec:
  encryptedData:
    node.session.auth.password: AgBAzGBeqDmGMvaQXYxTU8oHK2xIOTA8hnXzcEJaBMztQTqqmWkEpswVSz2eKHz1hfwle4uRJl2V7+64FlJqy8DTes+Qcjtv9yLXIBjqjdlUr3CbfyUXhcS5GmP83+bzzj1S3IHUpSiBLYGIqENwIKCYAHdBlEHKRAJTyG+knsr2M+N0mN7lL3+CyASbLSItpy1oIuoHLGQMtP+gaCwOkshzscv4cHU2odwyEDriDfHcRmT1KE0wp35Bid+Ludl2Pb6FarSM3kSrhpeF0NqgjVJT5ObBgX2TR0z7RQ+KDOQh7QoGstOPWJOZOTqlNq6kTFt7aXoHEtuQVG2eNLK0JnpSZpX3QZd8hpDJrpA0/KC69UEJAzrze2dUyis0ENuuwqj+Nf62/FgkBQ6sirgiRKN7nbyqLcFAu7wsr113NllsSMzuPUW7QgidH0DXjAJAspBka0NNsP2FmLnBQd8lGSNgotfD4fo2uHOZWaV2xtSpjswlwIwLcVSAY59/1oFohmi2Sz9Sb06lbRV1JIuq57b/8QDN/lzT5y4OVLfWcD1iAl7cek6ZDu3X4qJmg74O4xEO9e8Wc0cfjMmtSyFNH2NMRTYcokOD82UmJnFNhNyGTh0V5TNWXepb+wnBaaoffZG746663nysUQC14Yvf1tyEuQPOUfWMqzNExiKjXv/qgymLKIAyEskUrqZq+eAkkX2Woi1i98+0zmwXJm9VqQ==
    node.session.auth.username: AgCw6ZrgEO9MfxyF7aDjvIC1tGHUrMFePg7W4Cr+HSVI/uwBqeBrYPca488BPVE5Lj3vXJ1OacvAsrZl5/v5ec4YHm1KHDUoXUAgsyML/G6nIf7ZPScA5ugfH35QbP4RbMy1sKefFS6kEGeVXeYyrp6tZfE/qjbLPev3+LURfOQYQYncMOZA2AJ68eu5bxknZP4mSvwZDkJmUhYxrG0l5pTKW0QNr7kAMp0hEWc74G/Od5jqEM/BpZiOOd4zr+ghA7jz93kuRucTSL/6hsoyZjtlMbQPvem0ug6dX70+uh/1B7og3IAmzjtOtlOIHG0PhPdY1MG/ynE97AZDISPONf/naCfXlpkzfAquuipq04ZkxXO82jZVRechBRN82kneJ72D/tuAv6CKiBSZjktVN+MeV4U4ciXZWRFQxKdPs6n8lUfhqNqX3fl2s1rXiyAYHeWfZ/kp9LmdEEJG8Mxt0X7tI2eSShPhCL6soSExUoyTnmF4bf4g4tvB4SryzA5v6bX6KR2buZWDTFsFJVHRbrG33NUpAtOORe00R6YqZSOchT6GbTh3ubwCw5KUGgJ+XuQjvhsJslqOBxGsXkRLn6Br1VQh2yMba9Izm4rjtWVE2k+S+MlkwZHf5hPEYe8fhzZTwp7B4ALhqDeqkSOMaampqiwJ6yn+EmuTc7V3msko43eJCyWwggtAM6SxkHKpLWLuA7Irm15dN+Gg
  template:
    metadata:
      creationTimestamp: null
      name: chap-secret
      namespace: lazylibrarian
    type: kubernetes.io/iscsi-chap
