---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plex-secrets-role
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plex-secrets-binding
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: certificates
  apiGroup: ""
  namespace: plex
roleRef:
  kind: Role
  name: plex-secrets-role
  apiGroup: rbac.authorization.k8s.io
