---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~v2.3
spec:
  releaseName: traefik
  helmVersion: v3
  maxHistory: 3
  rollback:
    enable: false
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.4.3
  values:
    image:
      repository: traefik
      tag: 2.3.1
      pullPolicy: IfNotPresent
    env:
    - name: TZ
      value: America/Chicago
    installCRDs: true
    ingressClass:
      enabled: true
      isDefaultClass: "true"
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
    - --global.checknewversion=false
    - --global.sendanonymoususage=false
    additionalArguments:
    - --metrics.prometheus.entrypoint=web
    ports:
      traefik:
        expose: false
        port: 9000
        protocol: TCP
      web:
        expose: true
        exposedPort: 80
        port: 8000
        protocol: TCP
      websecure:
        expose: true
        exposedPort: 443
        port: 8443
        protocol: TCP
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.0.15
        externalTrafficPolicy: Local
    dnsPolicy: ClusterFirst
    logs:
      general:
        level: INFO
      access:
        enabled: true
    pilot:
      enabled: false
