---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  maxHistory: 3
  interval: 10m0s
  suspend: false
  releaseName: sonarr
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 6.0.2
  values:
    sonarr:
      image:
        organization: linuxserver
        repository: sonarr
        tag: 3.0.4.1019-ls6
      env:
        TZ: America/Chicago
        PUID: "1024"
        PGID: "100"
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: traefik-default-middlewares-chain@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls.options: traefik-secure-tlsoptions@kubernetescrd
        hosts:
        - host: sonarr.nathanpawelek.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: nathanpawelek-com-tls
      service:
        type: ClusterIP
        port: 8989
      configPath: /config
      persistence:
        type: statefulset
        config:
          enabled: true
          existingClaim: sonarr-config
        media:
          enabled: false
      additionalVolumes:
      - name: complete
        nfs:
          path: /volume1/Complete
          server: 192.168.0.150
      additionalVolumeMounts:
      - mountPath: /complete
        name: complete
      resources:
        requests:
          memory: 250Mi
        limits:
          memory: 500Mi
