---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: nzbget
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
