---
helmOperator:
  create: false
git:
  url: "git@github.com:npawelek/k8s-gitops"
  branch: "master"
image:
  repository: docker.io/raspbernetes/flux
  tag: 1.20.2
registry:
  rps: 50
  burst: 50
additionalArgs:
- --connect=ws://fluxcloud
# prometheus:
#   enabled: true
#   serviceMonitor:
#     create: true
#     interval: 30s
#     scrapeTimeout: 10s
#     namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
# dashboards:
#   enabled: true
dnsPolicy: ClusterFirst
dnsConfig:
  nameservers:
  - 192.168.0.10
  options:
  - name: ndots
    value: "1"
