apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: cert-manager
spec:
  encryptedData:
    config: AgAoelyVEadMuTpLZlyrV0/JwV9mFuEMJLNFWTTFFlUoqeXuEKLjtjfgUPg7p0x8PSzpw8HjnSJYAYLszXw24Hm/Vj4MwODnUtr0XJM3ZNH+2hgaKvBVsqjBpS+sNFq0PEHAPZkG+p3YgTJbH9dy9qznUJftqZqP6HXcXEPEg0aYKJPQWmFEFrKb5ZYwuXsFk4WpreawL361SVtWsjoKqbug6omBURTH8qiy9W3xL0GXOsRHJel38YVNeuwKdNX+y0Zii6AmV0BVwLL17nBiXw9h5tMpJnTgWhwPNHt7zIgvRYfRmeLx6WjDaw+ko16zi1fsY8qqUVzC0clbebQzhiq3b+xgE/7DeuTYfypABxFLMwiauukw1+C893jOFFvR0ZjYf+lkq3DduH/RRXpdtT4n0aPekpR77sho5aPyP4I10R2p9MTsi32po6jzX5aSkP/JaiOemYAGdDlQnPY80LWPfmAiuh34RGv7pkv/aYI3Ow0Xy3iJ6t4O4B+LpDraFSerg5c4maKk+5J+wuyTT9aRAYjkxbr67ZXKfuYg1NWXZb/KEbTcCMobpwnQBYUgBKABpX1UvBSnK8gjzco7s/haIowpA4wg6GgICXZkvKJ/N6Dj8ujd9/kifrrljc4iYDDWr151ObQnjNy8bAi028M/egOEG7Kk1W4EWJCzVXS/9USCdjaADK2irp3k5NMMsXxi9jymVc4cH42UwMZEZMgMYDqDYNyvrRF55gG1bA==
    credentials: AgCRV8ew0BBYdzAgUmOryE8WoE9mXvGF+AJxh5BGcQSKI/hXx1CUmxoTrx58TYDHc2mHBCE8jF42yu0220yPSex8DwbPUuJeX7zKx1/i1dkb179kJ3zYmKkspODRTJIBNlA/oEgeGxN9g6a/OjK5RPzspzS6S+Lt6pejVEISFBjSpUNRLM9D2Jr0EKmfBUsE818oBd4MyAO445HihZ/IwaTH6qPuxVfrxtrozfMkYpwLKfQ3Ptvpl5eoFDsP4aLQtfCg/OKW1qJW7aFsBDnoES2zGTn31EpuZ4B3lSeQlzGZwzu2Ql0WcgrZoYg/K1QguudY5Z+/0/2CNVirvFLdVpDcOvpqtQrjGUiQnQ686vK8XTBOZTG3/qn2Hwo3Sz3ayu//ZZ44h1WbSqnyjWkxOFJphha7+GZvjuWqlNJoRSe8zJ+iCKw3Vbfh5T/H4zvuOkG0LxQLKA+0oRx4s2YbNfWk4hvxUIPAWUfC5Bgb+e3cWVn04fVf2eecrFDFJ7gaL6vs0rMTKrBC/t/n3p9RoyoOS19dzttY/hAmAA2cjBXUNavZt4NqvqjiletEe6NoTC2oQ/Hnx6/ybuR7I1gj1CvJGiYH0JgymIbkbo2Vjrnyn/31auGw4q/o7s1mSXCaAFBxOrC/disb6VvlDekTba+LYQ3OhM1wF+YMA5QO9LWoh0zjK+c9aZJm1syLkxHrwVxEEeXXcVvg6KOjsAC3PEHlMHarFGkQ6ensUF0moYUs0klOFMEvJk5G/42zoMXSw9/POWgmMRJufaOdAAuKEZtjzYy629L/GdnRgeX651s5WVc/bNJtHjldQ6px9hajZ+7oXXJCjkLbM1IUmzWYGWzNwryEVQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: cert-manager
