---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  maxHistory: 3
  interval: 10m0s
  suspend: false
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: kubernetes-charts
        namespace: flux-system
      version: 1.10.3
  values:
    commandArgs:
    - --key-renew-period=0
